routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth::routes();

Route::middleware('throttle:byIP20')
    ->group(function () {
        Route::middleware('guest')
            ->group(function () {
                // Route::prefix('reg-agency/{registerReferral?}')
                //     // v-1
                //     ->group(function () {
                //         Route::get('/', [\App\Http\Controllers\Auth\RegisterController::class, 'showRegistrationForm'])->name('regAgency');
                //         Route::post('/', [\App\Http\Controllers\Auth\RegisterController::class, 'register']);
                //     });

                Route::prefix('login')
                    ->group(function () {
                        Route::get('/', [\App\Http\Controllers\Auth\LoginController::class, 'showLoginForm'])->name('login');
                        Route::post('/', [\App\Http\Controllers\Auth\LoginController::class, 'login']);
                    });

                Route::prefix('forgot')
                    ->name('forgot.')
                    ->group(function () {
                        Route::prefix('username')
                            ->name('username.')
                            ->group(function () {
                                // forgot.username.index
                                Route::get('/', [\App\Http\Controllers\ForgotController::class, 'viewForgotUsername'])->name('index');
                                // forgot.username.submit
                                Route::post('/', [\App\Http\Controllers\ForgotController::class, 'submitForgotUsername'])->name('submit');
                                // forgot.username.select
                                Route::get('/{forgotUsername}', [\App\Http\Controllers\ForgotController::class, 'selectForgotUsername'])->name('select');
                            });

                        Route::prefix('password')
                            ->name('password.')
                            ->group(function () {
                                // forgot.password.index
                                Route::get('/', [\App\Http\Controllers\ForgotController::class, 'viewForgotPassword'])->name('index');
                                // forgot.password.submit
                                Route::post('/', [\App\Http\Controllers\ForgotController::class, 'submitForgotPassword'])->name('submit');
                                Route::prefix('reset/{forgotPasswordToken}')
                                    ->name('reset.')
                                    ->group(function () {
                                        // forgot.password.reset.index
                                        Route::get('/', [\App\Http\Controllers\ForgotController::class, 'resetForgotPassword'])->name('index');
                                        // forgot.password.reset.save
                                        Route::post('/', [\App\Http\Controllers\ForgotController::class, 'resetForgotPassword'])->name('save');
                                    });
                            });
                    });


                // v-1
                // Route::prefix('reg-palmer/{unRegisteredCustomer}')
                //     ->group(function () {
                //         Route::get('/', [\App\Http\Controllers\CustomerController::class, 'toBeAgency'])->name('viewToBeAgency');
                //         Route::post('/', [\App\Http\Controllers\CustomerController::class, 'toBeAgency'])->name('saveToBeAgency');
                //     });

                Route::prefix('register')
                    ->group(function () {
                        // pendaftaran jamaah via link
                        Route::prefix('customer/{registerPalmerByToken?}')
                            ->group(function () {
                                // viewToBePalmer => register/customer/{registerPalmerByToken?}
                                Route::get('/', [\App\Http\Controllers\CustomerController::class, 'toBePalmer'])->name('viewToBePalmer');
                                // saveToBePalmer => register/customer/{registerPalmerByToken?}
                                Route::post('/', [\App\Http\Controllers\CustomerController::class, 'toBePalmer'])->name('saveToBePalmer');
                            });

                        // jamaah yang ingin menjadi agen
                        Route::prefix('to-be-agency/{unRegisteredCustomer}')
                            ->group(function () {
                                // viewToBeAgency => to-bo-agency/{unRegisteredCustomer}
                                Route::get('/', [\App\Http\Controllers\CustomerController::class, 'toBeAgency'])->name('viewToBeAgency');
                                // saveToBeAgency => to-bo-agency/{unRegisteredCustomer}
                                Route::post('/', [\App\Http\Controllers\CustomerController::class, 'toBeAgency'])->name('saveToBeAgency');
                            });
                    });
            });

        Route::prefix('logout')
            ->group(function () {
                Route::get('/', [\App\Http\Controllers\Auth\LoginController::class, 'logout'])->name('logout');
                Route::post('/', [\App\Http\Controllers\Auth\LoginController::class, 'logout']);
            });
    });

Route::middleware('throttle:bySession200')
    ->group(function () {
        // selectRegion => /select-region
        Route::get('/select-region', [App\Http\Controllers\RegionController::class, 'region'])->name('selectRegion');
        // selectProvince => /select-province
        Route::get('/select-province', [App\Http\Controllers\RegionController::class, 'province'])->name('selectProvince');
        // selectCity => /select-city
        Route::get('/select-city', [App\Http\Controllers\RegionController::class, 'city'])->name('selectCity');
        // selectBranchByArea => /select-branch-by-area
        Route::get('/select-branch-by-area', [App\Http\Controllers\BranchController::class, 'byArea'])->name('selectBranchByArea');
        // dashboard.data => dashboard/data
        Route::get('/dashboard-data', [App\Http\Controllers\HomeController::class, 'getData'])->name('dashboard.data');
        // programOptions => program-options
        Route::get('/program-options', [\App\Http\Controllers\BranchController::class, 'packageOptions'])->name('programOptions');
    });

Route::middleware('throttle:bySession50')
    ->group(function () {
        Route::get('/', [App\Http\Controllers\HomeController::class, 'welcome'])->name('welcome');
        Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

        Route::middleware('auth')
            ->group(function () {
                // dashboard => dashboard/
                Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'index'])
                    ->middleware(['auth.profile', 'auth.has.bank'])
                    ->name('dashboard');


                include 'files/branch.php';
                include 'files/package.php';
                include 'files/agency.php';
                include 'files/profile.php';
                include 'files/auth.php';
                include 'files/bank.php';
                include 'files/network.php';
                include 'files/customer.php';
                include 'files/bonus.php';
                include 'files/document.php';
            });
    });

app/Models/User.php
<?php

namespace App\Models;

use App\Casts\UppercaseCast;
use App\Models\Traits\ModelAddressTrait;
use App\Models\Traits\ModelIDTrait;
use App\Models\Traits\ModelPhoneTrait;
use App\Models\Traits\ModelToDetailTrait;
use App\Models\Traits\User\UserBonusTrait;
use App\Models\Traits\User\CustomerRegisterTrait;
use App\Models\Traits\User\UserStructureTrait;
use App\Models\Traits\User\UserBranchTrait;
use App\Models\Traits\User\UserStatusTrait;
use App\Models\Traits\User\UserTypeTrait;
// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Arr;
use Nette\Utils\Random;

// use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    // use HasApiTokens;
    use HasFactory, Notifiable;
    use ModelIDTrait, ModelAddressTrait, ModelPhoneTrait, ModelToDetailTrait;
    use UserTypeTrait, UserStatusTrait, UserBonusTrait, UserBranchTrait, UserStructureTrait, CustomerRegisterTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'username',
        'name',
        'email',
        'password',
        'user_group',
        'user_type',
        'status',
        'branch_id',
        'referral_id',
        'referred_count',
        'phone',
        'has_profile',
        'identity',
        'gender',
        'birth_date',
        'address',
        'village_id',
        'village_name',
        'district_name',
        'city_name',
        'province_name',
        'pos_code',
        'photo',
        'activated_at',
        'activated_by',
        'blocked_at',
        'blocked_by',
        'blocked_note',
        'banned_at',
        'banned_by',
        'banned_note',
        'rejected_at',
        'rejected_by',
        'rejected_note',
        'customer_id',
        'session_id',
        'link_token',
        'password_token',
        'password_token_at',
        'password_exp_at',
        'password_reset_at',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
        'session_id',
        'link_token',
        'password_token',
        'password_token_at',
        'password_exp_at',
        'password_reset_at',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'user_group' => 'integer',
        'user_type' => 'integer',
        'status' => 'integer',
        'referred_count' => 'integer',
        'has_profile' => 'boolean',
        'gender' => UppercaseCast::class,
        'email_verified_at' => 'datetime',
        'birth_date' => 'date',
        'password_token_at' => 'datetime',
        'password_exp_at' => 'datetime',
        'password_reset_at' => 'datetime',
    ];

    protected $ignoresDetail = [
        'username',
        'name',
        'email',
        'user_group',
    ];

    // relation
    public function referral()
    {
        return $this->belongsTo(static::class, 'referral_id', 'id')->byAgencyUser();
    }

    public function downlines()
    {
        return $this->hasMany(static::class, 'referral_id', 'id')->byAgencyUser();
    }

    public function referredCustomers()
    {
        return $this->hasMany(Customer::class, 'agency_id', 'id');
    }

    public function approvedCustomers()
    {
        return $this->hasMany(Customer::class, 'agency_id', 'id')->byApproved();
    }

    public function fromCustomer()
    {
        return $this->belongsTo(Customer::class, 'customer_id', 'id');
    }

    // public
    public function saveSession(string $sessionId): void
    {
        $this->timestamps = false;
        $this->session_id = $sessionId;
        $this->save();
    }

    // static
    public static function makeLinkToken(): string
    {
        $token = Random::generate(32);

        while (static::query()->byLinkToken($token)->count() > 0) {
            $token = Random::generate(32);
        }

        return $token;
    }

    public static function makeResetPasswordToken(): string
    {
        $token = Random::generate(32);

        while (static::query()->byResetPasswordToken($token)->count() > 0) {
            $token = Random::generate(32);
        }

        return $token;
    }

    // scope
    public function scopeByUsername(Builder $builder, string $username)
    {
        return $builder->where('username', '=', $username);
    }

    public function scopeByEmail(Builder $builder, string $email)
    {
        return $builder->where('email', '=', $email);
    }

    public function scopeByLinkToken(Builder $builder, string $linkToken)
    {
        return $builder->where(function ($w) use ($linkToken) {
            return $w->where('link_token', '=', $linkToken)
                ->orWhere('username', '=', $linkToken);
        });
    }

    public function scopeByResetPasswordToken(Builder $builder, string $token)
    {
        return $builder->where('password_token', '=', $token);
    }

    public function scopeByHasProfile(Builder $builder, bool $has): Builder
    {
        return $builder->where('has_profile', '=', $has);
    }

    // accessor
    public function getAgencyIsFromCustomerAttribute()
    {
        return ($this->agency_user && !empty($this->fromCustomer));
    }

    public function getGenderNameAttribute()
    {
        return Arr::get(GENDERS, $this->gender);
    }

    public function getUserMiddlewareAttribute()
    {
        if ($this->main_user) {
            $names = ['main'];
            if ($this->main_user_super) {
                $names[] = 'super';
            } elseif ($this->main_user_master) {
                $names[] = 'master';
            } else {
                $names[] = 'admin';
            }

            return implode('.', $names);
        }
        if ($this->branch_user) {
            return $this->branch_user_admin ? 'branch.admin' : 'branch.user';
        }
        if ($this->agency_user) return 'user.agency';

        return 'user.customer';
    }

    public function getHasReferralLinkAttribute()
    {
        return $this->agency_user || $this->branch_user_admin;
    }

    public function getReferralLinkUrlAttribute()
    {
        if ($this->has_referral_link) {
            // return route('regAgency', ['registerReferral' => $this->username]);
            // return route('viewToBePalmer', ['registerPalmerByToken' => $this->link_token]);
            return route('viewToBePalmer', ['registerPalmerByToken' => $this->username]);
        }

        return null;
    }

    public function getUserBankTypeAttribute()
    {
        $type = BANK_TYPE_AGENCY;

        if ($this->main_user) {
            $type = BANK_TYPE_MAIN;
        } elseif ($this->branch_user) {
            $type = BANK_TYPE_BRANCH;
        }

        return $type;
    }

    public function getUserBankUserIdAttribute()
    {
        if ($this->main_user) {
            return BANK_TYPE_MAIN;
        } elseif ($this->branch_user) {
            return $this->branch->id;
        }

        return $this->id;
    }

    public function getUserBanksAttribute()
    {
        return UserBank::query()
            ->byUser($this->user_bank_user_id)
            ->byType($this->user_bank_type)
            ->orderBy('is_active', 'desc')
            ->orderBy('bank_name')
            ->with('bank')
            ->get();
    }

    public function getAgencyActiveBankAttribute()
    {
        return $this->user_banks->where('is_active', '=', true)->first();
    }

    public function getHasActiveBankAttribute()
    {
        return ($this->user_banks->where('is_active', '=', true)->count() > 0);
    }
}

resources/views/home.blade.php
@php
    $user = isset($user) ? $user : Auth::user();
@endphp

@if ($user->main_user)
    @include('dashboard.main', ['user' => $user])
@elseif ($user->branch_user)
    @include('dashboard.branch', ['user' => $user])
@elseif ($user->agency_user)
    @include('dashboard.agency', ['user' => $user])
@endif

resources/views/login.blade.php
@extends('layouts.auth')

@section('content')
<form method="POST" action="{{ route('login') }}" data-alert-container="#alert-container" class="w-100 px-2 px-md-3 px-lg-4 px-xl-5">
    <div class="d-block" id="alert-container">
        @include('partials.alert')
    </div>
    @csrf
    <div class="mb-3">
        <label for="username" class="d-block mb-1">Username</label>
        <div class="input-group">
            <label for="username" class="input-group-text justify-content-center" style="width:44px;">
                <i class="fa fa-user"></i>
            </label>
            <input id="username" type="text" class="form-control" name="username" placeholder="Username" value="{{ session()->pull('loginFailed') }}" autocomplete="off" required autofocus>
        </div>
    </div>
    <div class="mb-3">
        <label for="password" class="d-block mb-1">Password</label>
        <div class="input-group">
            <label for="password" class="input-group-text justify-content-center" style="width:44px;">
                <i class="fa fa-key"></i>
            </label>
            <input id="password" type="password" class="form-control" name="password" placeholder="Password" autocomplete="off" data-icon-open="fa fa-eye" data-icon-close="fa fa-eye-slash" required>
            <label for="password" class="input-group-text cursor-pointer pwd-view justify-content-center" data-target="#password" style="width:44px;">
                <i class="pwd-icon"></i>
            </label>
        </div>
    </div>
    <div class="d-flex align-items-center justify-content-between flex-wrap mb-3 pb-2 border-bottom border-light">
        <div class="form-check py-2">
            <input class="form-check-input" type="checkbox" name="remember" id="remember" {{ old('remember') ? 'checked' : '' }}>
            <label class="form-check-label" for="remember">
                Ingatkan Saya
            </label>
        </div>
        <button type="submit" class="btn btn-primary">
            <i class="fa-solid fa-sign-in me-1"></i>Masuk
        </button>
    </div>
    <div class="text-center text-wrap">
        <div class="d-block mb-2">
            Lupa <a href="{{ route('forgot.username.index') }}">Username</a> atau <a href="{{ route('forgot.password.index') }}">Password</a> ?
        </div>
        <div>Ingin <a href="{{ route('viewToBePalmer') }}">Mendaftar</a> Umrah?</div>
    </div>
</form>
@endsection

@section('scripts')
<script>
    $(function() {
        const usrname = $('#username');
        if (usrname.val().length) {
            usrname[0].select();
        }
    });
</script>
@endsection

resources/views/password.blade.php
@php
    $user = isset($user) ? $user : Auth::user();
@endphp

@extends('layouts.app', [
    'user' => $user,
    'breadCrumbItems' => ['Password'],
    'docTitle' => 'Password'
])

@section('content')
<div class="d-block" id="alert-container">
    @include('partials.alert')
</div>
<div class="row justify-content-center">
    <div class="col-auto">
        <form class="card mb-3 fs-auto shadow-sm" method="POST" action="{{ route('password.update') }}" data-alert-container="#alert-container">
            <div class="card-header bg-secondary bg-gradient-darken text-light">
                <span class="">Ganti Password</span>
            </div>
            <div class="card-body">
                @csrf
                <label class="d-block required">Password Lama</label>
                <input type="password" name="old_password" class="form-control" placeholder="Password Lama" autocomplete="off" required autofocus>
            </div>
            <div class="card-body border-top">
                <div class="mb-2">
                    <label class="d-block required">Password Baru</label>
                    <input type="password" name="new_password" class="form-control" placeholder="Password Baru" autocomplete="off" required>
                </div>
                <div class="mb-2">
                    <label class="d-block required">Ketik Ulang Password Baru</label>
                    <input type="password" name="new_password_confirmation" class="form-control" placeholder="Ketik Ulang Password Baru" autocomplete="off" required>
                </div>
            </div>
            <div class="card-footer d-flex justify-content-center">
                <button type="submit" class="btn btn-sm btn-secondary">
                    <i class="fa-solid fa-save me-1"></i>
                    Simpan
                </button>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/profile.blade.php
@php
    $user = isset($user) ? $user : Auth::user();
    $isEdit = isset($isEdit) ? $isEdit : false;
    $breadCrumbItems = ['Profile'];
    if ($isEdit === true) {
        $breadCrumbItems[] = 'Edit';
    }
@endphp

@extends('layouts.app', [
    'user' => $user,
    'breadCrumbItems' => $breadCrumbItems,
    'docTitle' => 'Profile'
])

@section('content')
<div class="d-block" id="alert-container">
    @include('partials.alert')
</div>
@if ($isEdit === true)
    <form class="card mb-3 fs-auto" method="POST" action="{{ route('profile.update') }}" data-alert-container="#alert-container">
        <div class="card-body">
            @csrf
            <div class="row g-2">
                <div class="col-md-6">
                    <label class="d-block required">No. Identitas</label>
                    <input type="text" class="form-control" name="identity" value="{{ $user->identity }}" autocomplete="off" required autofocus>
                </div>
                <div class="col-md-6">
                    <label class="d-block required">Nama</label>
                    <input type="text" class="form-control" name="name" value="{{ $user->name }}" autocomplete="off" required>
                </div>
                <div class="col-sm-6 col-md-4 col-lg-3">
                    <label class="d-block required">Jns. Kelamin</label>
                    <select class="form-select" name="gender" autocomplete="off" required>
                        <option value="">-- Jns. Kelamin --</option>
                        @foreach (GENDERS as $key => $gender)
                            <option value="{{ $key }}" @optionSelected($key, $user->gender)>{{ $gender }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="col-sm-6 col-md-4 col-lg-3">
                    <label class="d-block required">Tgl. Lahir</label>
                    @include('partials.datepicker', [
                        'dateId' => 'birth-date',
                        'dateName' => 'birth_date',
                        'dateValue' => $user->birth_date,
                        'endDate' => \Carbon\Carbon::today(),
                        'required' => true,
                    ])
                </div>
                <div class="col-12">
                    <label class="d-block required">Alamat</label>
                    <input type="text" class="form-control" name="address" value="{{ $user->address }}" autocomplete="off" required>
                </div>
                <div class="col-12">
                    <label class="d-block required">Pilih Daerah</label>
                    <select class="form-select select2bs4 select2-custom" name="village_id" id="daerah-id" autocomplete="off" required>
                        @if (!empty($user->village_id))
                            <option value="{{ $user->village_id }}">
                                {{ $user->village_name }}, Kec. {{ $user->district_name }}, {{ $user->city_name }}, {{ $user->province_name }}
                            </option>
                        @endif
                    </select>
                    <div class="d-block d-sm-none" id="daerah-text"></div>
                </div>
                <div class="col-sm-6 col-md-4 col-lg-2">
                    <label class="d-block">Kode Pos</label>
                    <input type="text" name="pos_code" class="form-control" value="{{ $user->pos_code }}" placeholder="Kode Pos" autocomplete="off">
                </div>
                <div class="col-sm-6 col-md-8 col-lg-4">
                    <label class="d-block required">Handphone</label>
                    <input type="text" name="phone" class="form-control" value="{{ $user->phone }}" placeholder="Handphone" autocomplete="off">
                </div>
                <div class="col-lg-6">
                    <label class="d-block required">Email</label>
                    <input type="text" name="email" class="form-control" value="{{ $user->email }}" placeholder="Email" autocomplete="off">
                </div>
            </div>
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-sm btn-primary">
                <i class="fa-solid fa-save me-1"></i>
                Simpan
            </button>
            @if ($user->has_profile)
                <button type="button" class="btn btn-sm btn-warning" data-href="{{ route('profile.index') }}">
                    <i class="fa-solid fa-undo me-1"></i>
                    Batal
                </button>
            @endif
        </div>
    </form>

    @include('partials.guides.guide-list', [
        'guideList' => [
            view('partials.guides.required')->render(),
            view('partials.guides.select-area')->render(),
            view('partials.guides.handphone')->render(),
        ],
    ])
@else
    <div class="card fs-auto">
        <div class="card-header">
            <button type="button" class="btn btn-sm btn-primary" data-href="{{ route('profile.edit') }}">
                <i class="fa-solid fa-pencil me-1"></i>Edit
            </button>
        </div>
        <div class="card-body">
            <div class="row g-1 mb-2">
                <div class="col-auto flex-basis basis-120px basis-sm-150px d-flex justify-content-between">
                    <span class="pe-2">No. Identitas</span><span>:</span>
                </div>
                <div class="col-auto">
                    <div class="ps-3 ps-sm-0">{{ $user->identity }}</div>
                </div>
            </div>
            <div class="row g-1 mb-2">
                <div class="col-auto flex-basis basis-120px basis-sm-150px d-flex justify-content-between">
                    <span class="pe-2">Nama</span><span>:</span>
                </div>
                <div class="col-auto">
                    <div class="ps-3 ps-sm-0">{{ $user->name }}</div>
                </div>
            </div>
            <div class="row g-1 mb-2">
                <div class="col-auto flex-basis basis-120px basis-sm-150px d-flex justify-content-between">
                    <span class="pe-2">Jns. Kelamin</span><span>:</span>
                </div>
                <div class="col-auto">
                    <div class="ps-3 ps-sm-0">{{ $user->gender_name }}</div>
                </div>
            </div>
            <div class="row g-1 mb-2">
                <div class="col-auto flex-basis basis-120px basis-sm-150px d-flex justify-content-between">
                    <span class="pe-2">Tgl. Lahir</span><span>:</span>
                </div>
                <div class="col-auto">
                    <div class="ps-3 ps-sm-0">@translateDatetime($user->birth_date, 'd F Y')</div>
                </div>
            </div>
            <div class="row g-1 mb-2">
                <div class="col-auto flex-basis basis-120px basis-sm-150px d-flex justify-content-between">
                    <span class="pe-2">Alamat</span><span>:</span>
                </div>
                <div class="col-auto">
                    <div class="ps-3 ps-sm-0">{{ $user->address }}</div>
                </div>
            </div>
            <div class="row g-1 mb-2">
                <div class="col-auto flex-basis basis-120px basis-sm-150px d-flex justify-content-between">
                    <span class="pe-2">Desa / Kelurahan</span><span>:</span>
                </div>
                <div class="col-auto">
                    <div class="ps-3 ps-sm-0">{{ $user->village_name }}</div>
                </div>
            </div>
            <div class="row g-1 mb-2">
                <div class="col-auto flex-basis basis-120px basis-sm-150px d-flex justify-content-between">
                    <span class="pe-2">Kecamatan</span><span>:</span>
                </div>
                <div class="col-auto">
                    <div class="ps-3 ps-sm-0">{{ $user->district_name }}</div>
                </div>
            </div>
            <div class="row g-1 mb-2">
                <div class="col-auto flex-basis basis-120px basis-sm-150px d-flex justify-content-between">
                    <span class="pe-2">Kota / Kabupaten</span><span>:</span>
                </div>
                <div class="col-auto">
                    <div class="ps-3 ps-sm-0">{{ $user->city_name }}</div>
                </div>
            </div>
            <div class="row g-1 mb-2">
                <div class="col-auto flex-basis basis-120px basis-sm-150px d-flex justify-content-between">
                    <span class="pe-2">Propinsi</span><span>:</span>
                </div>
                <div class="col-auto">
                    <div class="ps-3 ps-sm-0">{{ $user->province_name }}</div>
                </div>
            </div>
            <div class="row g-1 mb-2">
                <div class="col-auto flex-basis basis-120px basis-sm-150px d-flex justify-content-between">
                    <span class="pe-2">Kode Pos</span><span>:</span>
                </div>
                <div class="col-auto">
                    <div class="ps-3 ps-sm-0">{{ $user->pos_code ?? '-' }}</div>
                </div>
            </div>
        </div>
    </div>
@endif
@endsection

@if ($isEdit === true)
@push('vendorCSS')
<link rel="stylesheet" href="{{ asset('vendor/bootstrap-datepicker-1.9.0/css/bootstrap-datepicker.standalone.min.css') }}">
<link rel="stylesheet" href="{{ asset('vendor/select2/css/select2.min.css') }}">
@endpush

@push('vendorJS')
<script src="{{ asset('vendor/bootstrap-datepicker-1.9.0/js/bootstrap-datepicker.min.js') }}"></script>
<script src="{{ asset('vendor/bootstrap-datepicker-1.9.0/locales/bootstrap-datepicker.id.min.js') }}"></script>
<script src="{{ asset('vendor/select2/js/select2.min.js') }}"></script>
<script src="{{ asset('vendor/select2/js/i18n/id.js') }}"></script>
@endpush

@push('scripts')
<script>
    let select_daerah;
    $(function() {
        select_daerah = $('#daerah-id');
        select_daerah.select2({
            theme: 'classic',
            placeholder: '-- Pilih Daerah --',
            allowClear: true,
            ajax: {
                url: function(params) {
                    params.current = select_daerah.val();
                    
                    return '{{ route("selectRegion") }}';
                },
                data: function (params) {
                    let dt = {
                        search: params.term,
                        current: params.current
                    };

                    return dt;
                },
                processResults: function (data) {
                    return {
                        results: data
                    };
                }
            }
        }).on('select2:select', function (e) {
            const data = e.params.data;
            const txt = $('#daerah-text');

            txt.html(data.text);

            if (data.text != '') {
                txt.addClass('mt-2');
            } else {
                txt.removeClass('mt-2');
            }
        });
    });
</script>
@endpush
@endif