routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth::routes();

Route::middleware('throttle:byIP20')
    ->group(function () {
        Route::middleware('guest')
            ->group(function () {
                // Route::prefix('reg-agency/{registerReferral?}')
                //     // v-1
                //     ->group(function () {
                //         Route::get('/', [\App\Http\Controllers\Auth\RegisterController::class, 'showRegistrationForm'])->name('regAgency');
                //         Route::post('/', [\App\Http\Controllers\Auth\RegisterController::class, 'register']);
                //     });

                Route::prefix('login')
                    ->group(function () {
                        Route::get('/', [\App\Http\Controllers\Auth\LoginController::class, 'showLoginForm'])->name('login');
                        Route::post('/', [\App\Http\Controllers\Auth\LoginController::class, 'login']);
                    });

                Route::prefix('forgot')
                    ->name('forgot.')
                    ->group(function () {
                        Route::prefix('username')
                            ->name('username.')
                            ->group(function () {
                                // forgot.username.index
                                Route::get('/', [\App\Http\Controllers\ForgotController::class, 'viewForgotUsername'])->name('index');
                                // forgot.username.submit
                                Route::post('/', [\App\Http\Controllers\ForgotController::class, 'submitForgotUsername'])->name('submit');
                                // forgot.username.select
                                Route::get('/{forgotUsername}', [\App\Http\Controllers\ForgotController::class, 'selectForgotUsername'])->name('select');
                            });

                        Route::prefix('password')
                            ->name('password.')
                            ->group(function () {
                                // forgot.password.index
                                Route::get('/', [\App\Http\Controllers\ForgotController::class, 'viewForgotPassword'])->name('index');
                                // forgot.password.submit
                                Route::post('/', [\App\Http\Controllers\ForgotController::class, 'submitForgotPassword'])->name('submit');
                                Route::prefix('reset/{forgotPasswordToken}')
                                    ->name('reset.')
                                    ->group(function () {
                                        // forgot.password.reset.index
                                        Route::get('/', [\App\Http\Controllers\ForgotController::class, 'resetForgotPassword'])->name('index');
                                        // forgot.password.reset.save
                                        Route::post('/', [\App\Http\Controllers\ForgotController::class, 'resetForgotPassword'])->name('save');
                                    });
                            });
                    });


                // v-1
                // Route::prefix('reg-palmer/{unRegisteredCustomer}')
                //     ->group(function () {
                //         Route::get('/', [\App\Http\Controllers\CustomerController::class, 'toBeAgency'])->name('viewToBeAgency');
                //         Route::post('/', [\App\Http\Controllers\CustomerController::class, 'toBeAgency'])->name('saveToBeAgency');
                //     });

                Route::prefix('register')
                    ->group(function () {
                        // pendaftaran jamaah via link
                        Route::prefix('customer/{registerPalmerByToken?}')
                            ->group(function () {
                                // viewToBePalmer => register/customer/{registerPalmerByToken?}
                                Route::get('/', [\App\Http\Controllers\CustomerController::class, 'toBePalmer'])->name('viewToBePalmer');
                                // saveToBePalmer => register/customer/{registerPalmerByToken?}
                                Route::post('/', [\App\Http\Controllers\CustomerController::class, 'toBePalmer'])->name('saveToBePalmer');
                            });

                        // jamaah yang ingin menjadi agen
                        Route::prefix('to-be-agency/{unRegisteredCustomer}')
                            ->group(function () {
                                // viewToBeAgency => to-bo-agency/{unRegisteredCustomer}
                                Route::get('/', [\App\Http\Controllers\CustomerController::class, 'toBeAgency'])->name('viewToBeAgency');
                                // saveToBeAgency => to-bo-agency/{unRegisteredCustomer}
                                Route::post('/', [\App\Http\Controllers\CustomerController::class, 'toBeAgency'])->name('saveToBeAgency');
                            });
                    });
            });

        Route::prefix('logout')
            ->group(function () {
                Route::get('/', [\App\Http\Controllers\Auth\LoginController::class, 'logout'])->name('logout');
                Route::post('/', [\App\Http\Controllers\Auth\LoginController::class, 'logout']);
            });
    });

Route::middleware('throttle:bySession200')
    ->group(function () {
        // selectRegion => /select-region
        Route::get('/select-region', [App\Http\Controllers\RegionController::class, 'region'])->name('selectRegion');
        // selectProvince => /select-province
        Route::get('/select-province', [App\Http\Controllers\RegionController::class, 'province'])->name('selectProvince');
        // selectCity => /select-city
        Route::get('/select-city', [App\Http\Controllers\RegionController::class, 'city'])->name('selectCity');
        // selectBranchByArea => /select-branch-by-area
        Route::get('/select-branch-by-area', [App\Http\Controllers\BranchController::class, 'byArea'])->name('selectBranchByArea');
        // dashboard.data => dashboard/data
        Route::get('/dashboard-data', [App\Http\Controllers\HomeController::class, 'getData'])->name('dashboard.data');
        // programOptions => program-options
        Route::get('/program-options', [\App\Http\Controllers\BranchController::class, 'packageOptions'])->name('programOptions');
    });

Route::middleware('throttle:bySession50')
    ->group(function () {
        Route::get('/', [App\Http\Controllers\HomeController::class, 'welcome'])->name('welcome');
        Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

        Route::middleware('auth')
            ->group(function () {
                // dashboard => dashboard/
                Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'index'])
                    ->middleware(['auth.profile', 'auth.has.bank'])
                    ->name('dashboard');


                include 'files/branch.php';
                include 'files/package.php';
                include 'files/agency.php';
                include 'files/profile.php';
                include 'files/auth.php';
                include 'files/bank.php';
                include 'files/network.php';
                include 'files/customer.php';
                include 'files/bonus.php';
                include 'files/document.php';
            });
    });

app/Models/Document.php
<?php

namespace App\Models;

use App\Models\Traits\ModelCodeTrait;
use App\Models\Traits\ModelIDTrait;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Document extends Model
{
    use HasFactory;
    use ModelIDTrait, ModelCodeTrait;

    public $timestamps = false;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'code',
        'name',
        'filename',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $casts = [];

    public const DOC_DISK = 'document';
    public const DOC_ASSET = 'files/';

    // accessor
    public function getDownloadUrlAttribute()
    {
        return asset(static::DOC_ASSET . $this->filename);
    }
}

app/Http/Controllers/DocumentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Document;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;

class DocumentController extends Controller
{
    public function index(Request $request)
    {
        $user = $request->user();

        return view('document.index', [
            'user' => $user,
            'documents' => Document::query()->orderBy('name')->get(),
        ]);
    }

    public function upload(Request $request)
    {
        if (!$request->isMethod('POST')) {
            return view('document.form');
        }

        $values = $request->except(['_token']);

        $validator = Validator::make($values, [
            'name' => ['required', 'string', 'max:100', 'unique:documents,name'],
            'doc_file' => ['required', 'file', 'mimetypes:application/pdf,application/msword,application/vnd.ms-office,application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'max:1024'],
        ], [
            'doc_file.mimetypes' => ':attribute yang dapat di-upload hanya file dengan format PDF dan MS-Word (.doc, .docx).',
            'doc_file.max' => ':attribute tidak boleh lebih dari :max kb (1 mb).',
        ], [
            'name' => 'Nama Dokumen',
            'doc_file' => 'File Dokumen',
        ]);

        if ($validator->fails()) {
            return response(errorMessageContent($validator, 'danger', 'Proses Upload Gagal.'), 400);
        }

        $isUploaded = false;
        $uploadedFile = null;
        $code = uniqid();

        DB::beginTransaction();
        try {
            $file = $request->file('doc_file');
            $ext = $file->extension();
            $filename = $code . ".{$ext}";
            $file->storePubliclyAs('/', $filename, Document::DOC_DISK);
            $values['code'] = $code;
            $values['filename'] = $filename;
            $isUploaded = true;
            $uploadedFile = $filename;

            Document::create($values);

            session([
                'message' => "Dokumen telah berhasil diunggah.",
                'messageClass' => 'success'
            ]);

            DB::commit();

            return response(route('document.index'), 200);
        } catch (\Exception $e) {
            DB::rollBack();
            $msg = isLive() ? MESSAGE_500 : $e->getMessage();

            if ($isUploaded && !empty($uploadedFile)) {
                Storage::disk(Document::DOC_DISK)->delete($uploadedFile);
            }

            return response(errorMessageContent($msg), 500);
        }
    }

    public function remove(Request $request)
    {
        if (!$request->isMethod('POST')) {
            return view('document.delete', [
                'document' => $request->document,
            ]);
        }

        $document = $request->document;
        $filename = $document->filename;

        DB::beginTransaction();
        try {
            $document->delete();
            Storage::disk(Document::DOC_DISK)->delete($filename);

            DB::commit();

            session([
                'message' => "Dokumen telah berhasil diunggah.",
                'messageClass' => 'success'
            ]);

            return response(route('document.index'), 200);
        } catch (\Exception $e) {
            DB::rollBack();

            $msg = isLive() ? MESSAGE_500 : $e->getMessage();

            return response(errorMessageContent($msg), 500);
        }
    }
}

resources/views/document/delete.blade.php
<form class="modal-content" method="POST" action="{{ route('document.destroy', ['document' => $document->id]) }}" data-alert-container="#alert-from-container" data-onfocus="#input-name" enctype="multipart/form-data">
    @include('partials.modals.modal-header', ['modalTitle' => 'Konfirmasi'])
    <div class="modal-body fs-auto">
        @csrf
        <div class="d-block" id="alert-from-container"></div>
        <div class="text-danger fs-5 text-center">
            Hapus Dokumen <span class="fw-bold">{{ $document->name }}</span> ?
        </div>
    </div>
    <div class="modal-footer justify-content-center py-1">
        <button type="submit" class="btn btn-sm btn-primary">
            <i class="fa-solid fa-trash"></i>
            Hapus
        </button>
        <button type="button" class="btn btn-sm btn-warning" data-bs-dismiss="modal">
            <i class="fa-solid fa-times"></i>
            Batal
        </button>
    </div>
</form>

resources/views/document/form.blade.php
<form class="modal-content" method="POST" action="{{ route('document.saveUpload') }}" data-alert-container="#alert-from-container" data-onfocus="#input-name" enctype="multipart/form-data">
    @include('partials.modals.modal-header', ['modalTitle' => 'Upload Dokumen'])
    <div class="modal-body fs-auto">
        @csrf
        <div class="d-block" id="alert-from-container"></div>
        <div class="row g-2">
            <div class="col-12">
                <label class="d-block required">Nama</label>
                <input type="text" id="input-name" name="name" class="form-control" value="" placeholder="Nama Dokumen" autocomplete="off" required>
            </div>
            <div class="col-12">
                <input type="file" name="doc_file" class="form-control" placeholder="File Dokumen" accept=".pdf,.doc,.docx" autocomplete="off" required>
            </div>
        </div>
    </div>
    <div class="modal-footer justify-content-center py-1">
        <button type="submit" class="btn btn-sm btn-primary">
            <i class="fa-solid fa-save"></i>
            Simpan
        </button>
        <button type="button" class="btn btn-sm btn-warning" data-bs-dismiss="modal">
            <i class="fa-solid fa-times"></i>
            Batal
        </button>
    </div>
</form>

resources/views/document/index.blade.php
@php
    $user = isset($user) ? $user : Auth::user();
    $title = $user->main_user ? 'Dokumen' : 'Download';
    $downloadName = $user->main_user ? 'document.download' : 'download.download';
    $canCRUD = ($user->main_user_super || $user->main_user_master);
@endphp

@extends('layouts.app', [
    'user' => $user,
    'breadCrumbItems' => [$title],
    'docTitle' => $title
])

@section('content')
@include('partials.alert')
@if ($canCRUD)
<div class="d-block mb-3 pb-2 border-bottom">
    <button type="button" class="btn btn-sm btn-glow" data-bs-toggle="modal" data-bs-target="#doc-modal" data-modal-url="{{ route('document.formUpload') }}" title="Tambah">
        <i class="fa-solid fa-plus" style="line-height: inherit"></i>
        Upload Dokumen
    </button>
</div>
@endif

<ul class="mb-0">
    @foreach ($documents as $document)
        <li class="ps-3 py-2">
            <span class="me-3">{{ $document->name }}</span>
            <span class="small">
                <a href="{{ $document->download_url }}" target="_blank" @if ($canCRUD) class="me-3" @endif>Download</a>
                @if ($canCRUD)
                <a href="#" class="text-danger" data-bs-toggle="modal" data-bs-target="#doc-modal" data-modal-url="{{ route('document.remove', ['document' => $document->code]) }}">Hapus</a>
                @endif
            </span>
        </li>
    @endforeach
</ul>
@endsection

@if ($canCRUD)
    @push('topContent')
        @include('partials.modals.modal', ['bsModalId' => 'doc-modal', 'scrollable' => true])        
    @endpush
@endif