routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth::routes();

Route::middleware('throttle:byIP20')
    ->group(function () {
        Route::middleware('guest')
            ->group(function () {
                // Route::prefix('reg-agency/{registerReferral?}')
                //     // v-1
                //     ->group(function () {
                //         Route::get('/', [\App\Http\Controllers\Auth\RegisterController::class, 'showRegistrationForm'])->name('regAgency');
                //         Route::post('/', [\App\Http\Controllers\Auth\RegisterController::class, 'register']);
                //     });

                Route::prefix('login')
                    ->group(function () {
                        Route::get('/', [\App\Http\Controllers\Auth\LoginController::class, 'showLoginForm'])->name('login');
                        Route::post('/', [\App\Http\Controllers\Auth\LoginController::class, 'login']);
                    });

                Route::prefix('forgot')
                    ->name('forgot.')
                    ->group(function () {
                        Route::prefix('username')
                            ->name('username.')
                            ->group(function () {
                                // forgot.username.index
                                Route::get('/', [\App\Http\Controllers\ForgotController::class, 'viewForgotUsername'])->name('index');
                                // forgot.username.submit
                                Route::post('/', [\App\Http\Controllers\ForgotController::class, 'submitForgotUsername'])->name('submit');
                                // forgot.username.select
                                Route::get('/{forgotUsername}', [\App\Http\Controllers\ForgotController::class, 'selectForgotUsername'])->name('select');
                            });

                        Route::prefix('password')
                            ->name('password.')
                            ->group(function () {
                                // forgot.password.index
                                Route::get('/', [\App\Http\Controllers\ForgotController::class, 'viewForgotPassword'])->name('index');
                                // forgot.password.submit
                                Route::post('/', [\App\Http\Controllers\ForgotController::class, 'submitForgotPassword'])->name('submit');
                                Route::prefix('reset/{forgotPasswordToken}')
                                    ->name('reset.')
                                    ->group(function () {
                                        // forgot.password.reset.index
                                        Route::get('/', [\App\Http\Controllers\ForgotController::class, 'resetForgotPassword'])->name('index');
                                        // forgot.password.reset.save
                                        Route::post('/', [\App\Http\Controllers\ForgotController::class, 'resetForgotPassword'])->name('save');
                                    });
                            });
                    });


                // v-1
                // Route::prefix('reg-palmer/{unRegisteredCustomer}')
                //     ->group(function () {
                //         Route::get('/', [\App\Http\Controllers\CustomerController::class, 'toBeAgency'])->name('viewToBeAgency');
                //         Route::post('/', [\App\Http\Controllers\CustomerController::class, 'toBeAgency'])->name('saveToBeAgency');
                //     });

                Route::prefix('register')
                    ->group(function () {
                        // pendaftaran jamaah via link
                        Route::prefix('customer/{registerPalmerByToken?}')
                            ->group(function () {
                                // viewToBePalmer => register/customer/{registerPalmerByToken?}
                                Route::get('/', [\App\Http\Controllers\CustomerController::class, 'toBePalmer'])->name('viewToBePalmer');
                                // saveToBePalmer => register/customer/{registerPalmerByToken?}
                                Route::post('/', [\App\Http\Controllers\CustomerController::class, 'toBePalmer'])->name('saveToBePalmer');
                            });

                        // jamaah yang ingin menjadi agen
                        Route::prefix('to-be-agency/{unRegisteredCustomer}')
                            ->group(function () {
                                // viewToBeAgency => to-bo-agency/{unRegisteredCustomer}
                                Route::get('/', [\App\Http\Controllers\CustomerController::class, 'toBeAgency'])->name('viewToBeAgency');
                                // saveToBeAgency => to-bo-agency/{unRegisteredCustomer}
                                Route::post('/', [\App\Http\Controllers\CustomerController::class, 'toBeAgency'])->name('saveToBeAgency');
                            });
                    });
            });

        Route::prefix('logout')
            ->group(function () {
                Route::get('/', [\App\Http\Controllers\Auth\LoginController::class, 'logout'])->name('logout');
                Route::post('/', [\App\Http\Controllers\Auth\LoginController::class, 'logout']);
            });
    });

Route::middleware('throttle:bySession200')
    ->group(function () {
        // selectRegion => /select-region
        Route::get('/select-region', [App\Http\Controllers\RegionController::class, 'region'])->name('selectRegion');
        // selectProvince => /select-province
        Route::get('/select-province', [App\Http\Controllers\RegionController::class, 'province'])->name('selectProvince');
        // selectCity => /select-city
        Route::get('/select-city', [App\Http\Controllers\RegionController::class, 'city'])->name('selectCity');
        // selectBranchByArea => /select-branch-by-area
        Route::get('/select-branch-by-area', [App\Http\Controllers\BranchController::class, 'byArea'])->name('selectBranchByArea');
        // dashboard.data => dashboard/data
        Route::get('/dashboard-data', [App\Http\Controllers\HomeController::class, 'getData'])->name('dashboard.data');
        // programOptions => program-options
        Route::get('/program-options', [\App\Http\Controllers\BranchController::class, 'packageOptions'])->name('programOptions');
    });

Route::middleware('throttle:bySession50')
    ->group(function () {
        Route::get('/', [App\Http\Controllers\HomeController::class, 'welcome'])->name('welcome');
        Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

        Route::middleware('auth')
            ->group(function () {
                // dashboard => dashboard/
                Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'index'])
                    ->middleware(['auth.profile', 'auth.has.bank'])
                    ->name('dashboard');


                include 'files/branch.php';
                include 'files/package.php';
                include 'files/agency.php';
                include 'files/profile.php';
                include 'files/auth.php';
                include 'files/bank.php';
                include 'files/network.php';
                include 'files/customer.php';
                include 'files/bonus.php';
                include 'files/document.php';
            });
    });

app/Models/Bank.php
<?php

namespace App\Models;

use App\Models\Traits\ModelActiveTrait;
use App\Models\Traits\ModelCodeTrait;
use App\Models\Traits\ModelIDTrait;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Bank extends Model
{
    use HasFactory;
    use ModelIDTrait, ModelCodeTrait, ModelActiveTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'code',
        'name',
        'logo',
        'is_active',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'is_active' => 'boolean',
    ];

    // accessor
    public function getLogoUrlAttribute()
    {
        return asset('images/bank/' . $this->logo);
    }
}

resources/views/banks/form.blade.php
<form class="modal-content" method="POST" action="{{ $postUrl }}" data-alert-container="#alert-from-container" data-onfocus="#account_no">
    @include('partials.modals.modal-header', ['modalTitle' => $modalTitle])
    <div class="modal-body fs-auto">
        @csrf
        <div class="d-block" id="alert-from-container"></div>
        @if ($formMode == 'create')
            <div class="row g-2">
                <div class="col-12">
                    <label class="d-block required">Bank</label>
                    <select name="bank_id" class="form-select" autocomplete="off" required>
                        <option value="">-- Pilih Bank --</option>
                        @foreach ($banks as $bank)
                            <option value="{{ $bank->id }}">{{ $bank->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="col-12">
                    <label class="d-block required">No. Rekening</label>
                    <input type="text" name="account_no" id="account_no" class="form-control" autocomplete="off" required>
                </div>
                <div class="col-12">
                    <label class="d-block required">Pemilik Rekening</label>
                    <input type="text" name="account_name" class="form-control" autocomplete="off" required>
                </div>
            </div>
        @else
            <div class="d-block text-center">
                <div class="mb-3">
                    <img src="{{ $userBank->bank->logo_url }}" alt="Logo" style="height: 50px;">
                </div>
                <div class="fw-bold">{{ $userBank->bank_name }}</div>
                <div>{{ $userBank->account_no }}</div>
                <div>{{ $userBank->account_name }}</div>
                <div class="mt-3 fw-bold">{{ ($formMode == 'enable') ? '' : 'Non ' }} Aktifkan rekening bank ?</div>
            </div>
        @endif
    </div>
    <div class="modal-footer justify-content-center py-1">
        <button type="submit" class="btn btn-sm btn-{{ ($formMode == 'disable') ? 'danger' : 'primary' }}">
            <i class="fa-solid fa-{{ ($formMode == 'create') ? 'save' : (($formMode == 'enable') ? 'circle-check' : 'ban') }}"></i>
            {{ ($formMode == 'create') ? 'Simpan' : ((($formMode == 'enable') ? '' : 'Non ') . 'Aktifkan') }}
        </button>
        <button type="button" class="btn btn-sm btn-warning" data-bs-dismiss="modal">
            <i class="fa-solid fa-times"></i>
            Batal
        </button>
    </div>
</form>

resources/views/banks/index.blade.php
@php
    $user = isset($user) ? $user : Auth::user();
    $banks = $user->user_banks;
@endphp

@extends('layouts.app', [
    'user' => $user,
    'breadCrumbItems' => ['Rekening Bank'],
    'docTitle' => 'Rekening Bank'
])

@section('content')
@include('partials.alert')

@canBankAction('create', $user)
<div class="d-block mb-2">
    <button type="button" class="btn btn-sm btn-glow" data-bs-toggle="modal" data-bs-target="#my-modal" data-modal-url="{{ route('bank.create') }}">
        <i class="fa-solid fa-plus"></i>
        Tambah
    </button>
</div>
@endcanBankAction

<table class="table mb-2 fs-auto" id="table">
    <thead class="d-none">
        <tr>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach ($banks as $bank)
            <tr>
                <td>
                    <div class="row g-2">
                        <div class="col-lg-2 position-relative">
                            <div class="text-center text-sm-start">
                                <img src="{{ $bank->bank->logo_url }}" alt="Logo" style="height:auto; width:auto; max-width:80%; max-height:50px;">
                            </div>
                        </div>
                        @php
                            $color = !$bank->is_active ? 'text-danger' : '';
                        @endphp
                        <div class="col-lg-10 text-center text-sm-start ">
                            <div class="{{ $color }}">
                                <div class="fw-bold">{{ $bank->bank_name }}</div>
                                <div>{{ $bank->account_no }}</div>
                                <div>{{ $bank->account_name }}</div>
                            </div>
                            @if (!$bank->is_active)
                                @canBankAction('enable', $user)
                                <div class="mt-1">
                                    <a href="javascript:;" class="link-primary" data-bs-toggle="modal" data-bs-target="#my-modal" data-modal-url="{{ route('bank.enable', ['userBank' => $bank->id]) }}">Aktifkan</a>
                                </div>
                                @endcanBankAction
                            @else
                                @if ($user->main_user)
                                    @canBankAction('disable', $user)
                                    <div class="mt-1">
                                        <a href="javascript:;" class="link-secondary" data-bs-toggle="modal" data-bs-target="#my-modal" data-modal-url="{{ route('bank.disable', ['userBank' => $bank->id]) }}">Non Aktifkan</a>
                                    </div>
                                    @endcanBankAction
                                @endif
                            @endif
                        </div>
                    </div>
                </td>
            </tr>
        @endforeach
    </tbody>
</table>
@endsection

@if (canBankAction('create', $user) || canBankAction('enable', $user) || canBankAction('disable', $user))
@push('topContent')
    @include('partials.modals.modal', ['bsModalId' => 'my-modal', 'scrollable' => true])
@endpush
@endif

@push('vendorCSS')
<link rel="stylesheet" href="{{ asset('vendor/datatables/DataTables-1.11.4/css/dataTables.bootstrap5.min.css') }}">
@endpush

@push('styles')
<link rel="stylesheet" href="{{ asset('css/table.css') }}">
@endpush

@push('vendorJS')
<script src="{{ asset('vendor/datatables/datatables.min.js') }}"></script>
<script src="{{ asset('vendor/datatables/DataTables-1.11.4/js/dataTables.bootstrap5.min.js') }}"></script>
@endpush

@push('scripts')
<script>
    $(function() {
        $('#table').DataTable({
            dom: 'lfr<"table-responsive"t>ip',
            processing: false,
            serverSide: false,
            searching: false,
            ordering: false,
            paging: false,
            info: false,
            lengthChange: false,
            language: {!! json_encode(__('datatable')) !!},
        });
    });
</script>
@endpush